import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useQuery} from "../src/hooks/useQuery";
import {useState} from "react";

export default function Home() {
  const [code, setCode] = useState<string>('200');
  const [message, setMessage] = useState<string>('');
  const {data, isLoading, error} = useQuery('http://localhost:3000/api/hello', { code, message})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <input value={code} onChange={({target}) => setCode(target.value)} />
          <input value={message} onChange={({target}) => setMessage(target.value)} />
        </div>
        {isLoading && <>Загрузка...</>}
        {error && <div style={{color: "red"}}>{error}</div>}
        {(!isLoading && !error) && data?.message}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
